### PR TITLE
ci: linux aarch64 native-image build

### PR DESCRIPTION
**Pull request by TimoKramer**
With this PR I added the linux aarch64 native-image build to tools-deps-native. I've also bumped the Graalvm version to the latest jdk-11 release.

My Circleci-builds:
https://app.circleci.com/pipelines/github/TimoKramer/tools-deps-native/14/workflows/3941c3dc-f9fd-461d-b9b3-27ebd77aec59

### CODE REVIEW

**Comment by TimoKramer** [comment]
@borkdude do you think this makes sense for you?

**Comment by borkdude** [comment]
I think we should bump GraalVM to JDK 21 similar to what babashka does. jdk11 is no longer supported, which is also why Appveyor doesn't work anymore.

**Comment by borkdude** [comment]
Other than that I think it makes sense!

**Comment by TimoKramer** [comment]
I think it's good now. Updated the build environment.

**Comment by borkdude** [comment]
Perfect, thanks!

**Pull request merged**
